changelog:
  exclude:
    labels:
      - skip-changelog
      - dependencies
    authors:
      - dependabot
  categories:
    - title: Breaking changes
      labels:
        - breaking
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Bug fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Other changes
      labels:
        - "*"
